name: scanner
services:

  activemq-classic:
      image: apache/activemq-classic:5.18.6
      restart: always
      container_name: activemq-classic-cnr
      ports:
        - 61616:61616
        - 8161:8161

#  mysql:
#    container_name: mysql-aero-cnr
#    restart: always
#    ports:
#      - 3306:3306
#    environment:
#      - MYSQL_ROOT_PASSWORD=lera
#     - MYSQL_DATABASE=aero
#    image: mysql:lts

  scanner:
      image: scanner-17-img:v1
      restart: always
      container_name: scanner-v1-cnr
      ports:
          - 81:81